apiVersion: v1
kind: ConfigMap
metadata:
  name: seasons-nginx-config
  namespace: ingress-nginx
data:
  resolver-addresses: "34.85.19.247"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: seasons-nginx-ingress
  namespace: ingress-nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: seasons-nginx-ingress
  rules:
    - http:
        paths:
          - path: /summer
            pathType: Prefix
            backend:
              service:
                name: summer-svc
                port:
                  number: 80
          - path: /winter
            pathType: Prefix
            backend:
              service:
                name: winter-svc
                port:
                  number: 80
