apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1

spec:
  replicas: 2
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: nginx-example
        image: nginx:1.19.0
        ports:
        - name: "app1-port"
          containerPort: 8080
        - name: "app2-port"
          containerPort: 8081
        resources:
        #   limits:
        #     cpu: "2"
        #     memory: "4096Mi"
        #   requests:
        #     cpu: "2"
        #     memory: "4096Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: app1
spec: 
  type: ClusterIP
  selector:
    app: app1
  ports:
  - name: "app1-port"
    protocol: "TCP"
    port: 8080
    targetPort: "http"
  - name: "app2-port"
    protocol: "TCP"
    port: 8081
    targetPort: "https"
