apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - name: https
          containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: app-service-0
spec: 
  type: ClusterIP
  selector:
    app: nginx
  ports:
  - name: app-port
    protocol: TCP
    port: 443
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: app-service-1
spec: 
  type: ClusterIP
  selector:
    app: nginx
  ports:
  - name: app-port
    protocol: TCPdata
    port: 80
    targetPort: 8080