apiVersion: apps/v1
kind: Deployment
metadata:
  name: summer-dep
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: summer
  template:
    metadata:
      labels:
        app: summer
    spec:
      containers:
      - name: summer
        image: nginxdemos/nginx-hello:plain-text
        ports:
        - name: http
          containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: summer-svc
  namespace: default
spec: 
  type: ClusterIP
  selector:
    app: summer
  ports:
  - name: app-port
    protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: winter-dep
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: winter
  template:
    metadata:
      labels:
        app: winter
    spec:
      containers:
      - name: winter
        image: nginxdemos/nginx-hello:plain-text
        ports:
        - name: http
          containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: winter-svc
  namespace: default
spec: 
  type: ClusterIP
  selector:
    app: winter
  ports:
  - name: app-port
    protocol: TCP
    port: 80
    targetPort: 8080