apiVersion: apps/v1
kind: Deployment
metadata:
  name: app0
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app0
  template:
    metadata:
      labels:
        app: app0
    spec:
      containers:
      - name: nginx-example
        image: nginx:1.19.0
        ports:
        - name: "app0-port"
          containerPort: 8080
        - name: "app1-port"
          containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec: 
  type: ClusterIP
  selector:
    app: app-service
  ports:
  - name: "app0-port"
    protocol: "TCP"
    port: 8080
    targetPort: "http"
  - name: "app1-port"
    protocol: "TCP"
    port: 8081
    targetPort: "https"
