apiVersion: v1
kind: Service
metadata:
  name: summer-np
  namespace: default
spec: 
  type: NodePort
  selector:
    app: summer
  ports:
  - name: node-port
    protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30080
---
apiVersion: v1
kind: Service
metadata:
  name: summer-lb
  namespace: default
spec: 
  type: LoadBalancer
  selector:
    app: summer
  ports:
  - name: lb-port
    protocol: TCP
    port: 80
    targetPort: 8080