apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: neg-ingress
  namespace: default
spec:
  rules:
  - host: summerseason.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: summer-svc
            port:
              number: 80
