apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: route
spec:
  parentRefs:
  - name: gateway
  hostnames:
  - "ingress-seasons.com"
  rules:
  - matches:
    - path:
        value: /
    backendRefs:
      - name: summer-svc
        port: 80
